[package]
name = "shortness-of-lifetimes"
version = "0.1.0"
authors = ["phxtho <phathopukwana@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indicatif = "0.15.0"
chrono = "0.4"
structopt = "0.3.21"